### GENERAL SETTINGS ###

# Site settings
title: Horst
description: "Horst's description"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://horst.rocks"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
# social:
#   - title: dribbble
#     url:
#   - title: facebook
#     url:
#   - title: twitter
#     url:
#   - title: instagram
#     url:
#   - title: tumblr
#     url:
social:
  - title: facebook
    url:
  - title: twitter
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Budapester Straße 46,
    - 10787 Berlin
    - Deutschland
email: horst@horst.rocks
tel: +49 30 200070025

### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Felix Röser
    position: Architect & Developer
    text: Lorem Ipsum Rocket Science
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:felix@horst.rocks
      - title: twitter
        url: http://twitter.com/felixroeser
  - name: Jan Rösner
    position: Architect & Developer
    text: Lorem Ipsum Quantum Science
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:jan@horst.rocks
      - title: twitter
        url: http://twitter.com/janroesner
  - name: Aishwarya Singhal
    position: Architect & Developer
    text: Lorem Ipsum Genius
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:aish@horst.rocks
      - title: twitter
        url: http://twitter.com/aishwaryasinghal

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Some interesting teaser text that makes the user curious, limp and want nothing but read more about Horst."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "This is such an awesome piece of software, that I immediately decided to throw capital onto it. The founders and developers are ingenius, fabulous, simply awesome. I literally HAD to invest this 500 million into that life changing piece of art, science and pure awesomeness."
    author: Marc Andreessen
    position: Investment God
