# Site settings
title: Horst Rocks
email: horst@horst.rocks
description: > # this means to ignore newlines until "baseurl:"
  Horst is like Otto but for bootstrapping organizational setups.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://horst.rocks" # the base hostname & protocol for your site
twitter_username: horstrocks
github_username:  horstrocks

# Build settings
markdown: kramdown
